import io
import re
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def _strip_html(html):
    if not html:
        return ''
    text = re.sub(r'<br\s*/?>', '\n', html)
    text = re.sub(r'</p>', '\n', text)
    text = re.sub(r'</h[1-6]>', '\n', text)
    text = re.sub(r'</li>', '\n', text)
    text = re.sub(r'<li[^>]*>', '• ', text)
    text = re.sub(r'<[^>]+>', '', text)
    for ent, rep in [('&amp;', '&'), ('&lt;', '<'), ('&gt;', '>'), ('&nbsp;', ' '), ('&quot;', '"')]:
        text = text.replace(ent, rep)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def generate_docx(proposal):
    doc = Document()

    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    # Title
    h = doc.add_heading(proposal['project_title'], 0)
    for run in h.runs:
        run.font.color.rgb = RGBColor(0x4f, 0x46, 0xe5)

    # Subtitle
    p = doc.add_paragraph()
    run = p.add_run(f"Prepared for: {proposal['client_name']}")
    run.font.color.rgb = RGBColor(0x6b, 0x72, 0x80)
    run.italic = True

    doc.add_paragraph('─' * 55)

    if proposal.get('price'):
        p = doc.add_paragraph()
        p.add_run('Investment:  ').bold = True
        p.add_run(f"${float(proposal['price']):,.2f}")
    if proposal.get('timeline'):
        p = doc.add_paragraph()
        p.add_run('Timeline:    ').bold = True
        p.add_run(proposal['timeline'])
    p = doc.add_paragraph()
    p.add_run('Status:      ').bold = True
    p.add_run(proposal.get('status', 'Draft'))

    doc.add_paragraph('─' * 55)
    doc.add_paragraph()

    content_text = _strip_html(proposal.get('content') or proposal.get('description') or '')
    if content_text:
        for line in content_text.split('\n'):
            line = line.strip()
            if not line:
                doc.add_paragraph()
                continue
            if line.startswith('•'):
                doc.add_paragraph(line[1:].strip(), style='List Bullet')
            else:
                doc.add_paragraph(line)
    else:
        doc.add_paragraph('No content available.')

    doc.add_paragraph()
    doc.add_paragraph('─' * 55)
    p = doc.add_paragraph()
    run = p.add_run('Generated by Freelancer Proposal Builder')
    run.font.color.rgb = RGBColor(0x9c, 0xa3, 0xaf)
    run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
