import io
import re
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.units import inch
from reportlab.lib import colors


def _strip_html(html):
    if not html:
        return ''
    text = re.sub(r'<br\s*/?>', '\n', html)
    text = re.sub(r'</p>', '\n', text)
    text = re.sub(r'</h[1-6]>', '\n', text)
    text = re.sub(r'</li>', '\n', text)
    text = re.sub(r'<li[^>]*>', '• ', text)
    text = re.sub(r'<[^>]+>', '', text)
    for ent, rep in [('&amp;', '&'), ('&lt;', '<'), ('&gt;', '>'), ('&nbsp;', ' '), ('&quot;', '"')]:
        text = text.replace(ent, rep)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def generate_pdf(proposal):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=1 * inch, rightMargin=1 * inch,
        topMargin=1 * inch, bottomMargin=1 * inch
    )

    styles = getSampleStyleSheet()
    brand = colors.HexColor('#4f46e5')
    dark = colors.HexColor('#1e1b4b')
    muted = colors.HexColor('#6b7280')
    body_color = colors.HexColor('#374151')

    title_s = ParagraphStyle('PT', parent=styles['Title'],
                             fontSize=24, textColor=dark, spaceAfter=4, fontName='Helvetica-Bold')
    sub_s = ParagraphStyle('PS', parent=styles['Normal'],
                           fontSize=11, textColor=muted, spaceAfter=16, italic=True)
    h2_s = ParagraphStyle('PH2', parent=styles['Normal'],
                          fontSize=13, textColor=brand, spaceBefore=14, spaceAfter=4,
                          fontName='Helvetica-Bold')
    body_s = ParagraphStyle('PB', parent=styles['Normal'],
                            fontSize=10.5, textColor=body_color, spaceAfter=6, leading=15)
    label_s = ParagraphStyle('PL', parent=styles['Normal'],
                             fontSize=8.5, textColor=muted, spaceAfter=2)

    story = []

    story.append(Paragraph(proposal['project_title'], title_s))
    story.append(Paragraph(f"Prepared for <b>{proposal['client_name']}</b>", sub_s))
    story.append(HRFlowable(width='100%', thickness=2, color=brand, spaceAfter=14))

    meta_rows = []
    if proposal.get('price'):
        meta_rows.append(['Investment', f"${float(proposal['price']):,.2f}"])
    if proposal.get('timeline'):
        meta_rows.append(['Timeline', proposal['timeline']])
    meta_rows.append(['Status', proposal.get('status', 'Draft')])

    t = Table(meta_rows, colWidths=[1.4 * inch, 5.1 * inch])
    t.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (0, -1), brand),
        ('TEXTCOLOR', (1, 0), (1, -1), body_color),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.HexColor('#f5f3ff'), colors.white]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.18 * inch))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#e5e7eb'), spaceAfter=14))

    content_text = _strip_html(proposal.get('content') or proposal.get('description') or '')
    if content_text:
        for line in content_text.split('\n'):
            line = line.strip()
            if not line:
                story.append(Spacer(1, 0.06 * inch))
                continue
            if line.startswith('•'):
                story.append(Paragraph(line, body_s))
            else:
                story.append(Paragraph(line, body_s))
    else:
        story.append(Paragraph('No content provided.', body_s))

    story.append(Spacer(1, 0.25 * inch))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#e5e7eb'), spaceAfter=6))
    story.append(Paragraph('Generated by Freelancer Proposal Builder', label_s))

    doc.build(story)
    buf.seek(0)
    return buf
