import re


def _strip_html(html):
    if not html:
        return ''
    text = re.sub(r'<br\s*/?>', '\n', html)
    text = re.sub(r'</p>', '\n', text)
    text = re.sub(r'</h[1-6]>', '\n', text)
    text = re.sub(r'</li>', '\n', text)
    text = re.sub(r'<li[^>]*>', '  • ', text)
    text = re.sub(r'<[^>]+>', '', text)
    for ent, rep in [('&amp;', '&'), ('&lt;', '<'), ('&gt;', '>'), ('&nbsp;', ' '), ('&quot;', '"')]:
        text = text.replace(ent, rep)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def generate_txt(proposal):
    sep = '=' * 60
    thin = '-' * 60
    lines = [
        sep,
        proposal['project_title'].upper(),
        f"Prepared for: {proposal['client_name']}",
        sep,
        '',
    ]
    if proposal.get('price'):
        lines.append(f"Investment:  ${float(proposal['price']):,.2f}")
    if proposal.get('timeline'):
        lines.append(f"Timeline:    {proposal['timeline']}")
    lines.append(f"Status:      {proposal.get('status', 'Draft')}")
    lines += [thin, '']

    content = _strip_html(proposal.get('content') or proposal.get('description') or '')
    lines.append(content if content else 'No content available.')
    lines += ['', thin, 'Generated by Freelancer Proposal Builder']

    return '\n'.join(lines)
